// <auto-generated />
namespace LatihanBook.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class First_Insert_Data : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(First_Insert_Data));
        
        string IMigrationMetadata.Id
        {
            get { return "201805230632397_First_Insert_Data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
